# Generated by Django 4.0.3 on 2022-08-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Rasm uchun link')),
                ('text', models.TextField(max_length=1024, verbose_name='Rasmdan keyingi matn')),
                ('type', models.CharField(choices=[('univer', 'Universitet'), ('house', 'American House')], max_length=10)),
            ],
            options={
                'db_table': 'About',
            },
        ),
        migrations.CreateModel(
            name='Chance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Imkoniyatlar rasmi uchun link')),
                ('text', models.TextField(max_length=1024, verbose_name='Rasmdan keyingi matn')),
            ],
            options={
                'db_table': 'Chance',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Kupon rasmi uchun link')),
                ('text', models.TextField(max_length=1024, verbose_name='Rasmdan keyingi matn')),
            ],
            options={
                'db_table': 'Coupon',
            },
        ),
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image_url', models.URLField(verbose_name='Rasm uchun link')),
                ('text', models.TextField(max_length=1024, verbose_name='Rasmdan keyingi matn')),
                ('profile', models.URLField(verbose_name="Bog'lanish uchun")),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'db_table': 'Fakultet',
            },
        ),
    ]
