# Generated by Django 4.0.3 on 2022-08-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_about_image_url_about_telegraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_url',
            field=models.URLField(null=True, verbose_name='Rasm uchun link'),
        ),
    ]
